# Generated by Django 5.2 on 2025-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_factura_cambio_alter_empleado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
